services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data